# Generated by Django 3.0.6 on 2020-07-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(null=True, upload_to='avatar/')),
                ('name', models.CharField(max_length=40)),
                ('profession', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('post_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
