# Generated by Django 3.0.6 on 2020-07-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='proffesion',
            field=models.CharField(max_length=40),
        ),
    ]
