# Generated by Django 3.0.6 on 2020-07-23 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20200722_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='proffesion',
            new_name='profession',
        ),
    ]
